version: '3.5'

services:
  db:
    image: postgres
    container_name: nyc-restaurant-grades-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  web:
    image: bswinnerton/nyc-restaurant-grades
    container_name: nyc-restaurant-grades-web
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
      - RAKE_ENV=production
    expose:
      - 3000
    networks:
      - backend
    volumes:
      - www_data:/var/www/app/
      - ./master.key:/var/www/app/config/master.key:ro
  nginx:
    image: nginx
    container_name: nyc-restaurant-grades-nginx
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - www_data:/var/www/app/
    networks:
      - web
      - backend
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:nyc-restaurant-grades.com"

volumes:
  db_data:
  www_data:

networks:
  backend:
  web:
    external: true
