modules:
  # Default IF-MIB interfaces table with ifIndex.
  if_mib:
    walk: [sysUpTime, interfaces, ifXTable]
  # Interfaces if ifAlias is unique.
  if_mib_ifalias:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        new_index: ifAlias
  # Interfaces if ifDescr is unique.
  if_mib_ifdescr:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        new_index: ifDescr
  # Interfaces if ifName is unique.
  if_mib_ifname:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        new_index: 1.3.6.1.2.1.31.1.1.1.1 # ifName

# Ubiquiti / AirMAX
#
# https://dl.ubnt.com/firmwares/airos-ubnt-mib/ubnt-mib.zip
#
  ubiquiti_airmax:
    version: 1
    walk:
      - sysUpTime
      - interfaces
      - ifXTable
      - 1.3.6.1.4.1.41112.1.4 # ubntAirMAX
    lookups:
      - old_index: ifIndex
        new_index: ifDescr

# Ubiquiti / UniFi
#
# http://dl.ubnt-ut.com/snmp/UBNT-MIB
# http://dl.ubnt-ut.com/snmp/UBNT-UniFi-MIB
#
  ubiquiti_unifi:
    walk:
      - sysUpTime
      - interfaces
      - ifXTable
      - 1.3.6.1.4.1.41112.1.6 # ubntUniFi

  ubiquiti_edgemax:
    walk:
      - sysUpTime
      - interfaces
      - ifXTable
      - 1.3.6.1.4.1.2021 # UCD-SNMP-MIB
      - 1.3.6.1.2.1.4 # RFC1213-MIB
    lookups:
      - old_index: ifIndex
        new_index: ifDescr
