version: '2.2'
services:
  mongo:
    image: mongo:3.4
    container_name: unifi_mongo
    restart: always
    volumes:
      - db:/data/db
    networks:
      - unifi
  controller:
    image: jacobalberty/unifi:stable
    container_name: unifi_controller
    restart: always
    depends_on:
      - mongo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/unifi/data
    networks:
      - unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  exporter:
    image: bswinnerton/unifi_exporter
    container_name: unifi_exporter
    restart: always
    depends_on:
      - controller
    command: -config.file /etc/unifi_exporter/config.yml
    volumes:
      - exporter_config:/etc/unifi_exporter
    ports:
      - 9130:9130

volumes:
  db:
  data:
  exporter_config:

networks:
  unifi:
